language: node_js
node_js:
- stable
sudo: false
script:
- npm test
branches:
  only:
  - "/^\\d+\\.\\d+/"
deploy:
  provider: npm
  email: manager@mathjax.org
  api_key:
    secure: rdvJ27qbw4DZJl49NSf/ybkeHWNWnk2MajS8Y8bMKwI8RaDyEGcAm3frA+CfBw+YHWl71KRJlQHL69YgVwp1nMSzKrGOpwrbL3TMFrFMdBC6tJ30dX1HSvAg9eU5K12E5672MM8qkTwJdYXsvEcyYlzRR+sogR8jTWRl3APuAwY=
  on:
    tags: true
